[package]
name = "virtuc"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.14"
nom = "7.1"
inkwell = { version = "0.7.1", features = ["llvm19-1"] }
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"
proptest = "1.0"
